export let videos = [
  {
    id: 0,
    name: "Cat 1",
    img: "../assets/thumbnails/cat1.PNG",
    src: "../assets/videos/cat_1.mp4",
    bookmarked: false,
  },
  {
    id: 1,
    name: "Cat 2",
    img: "../assets/thumbnails/cat2.PNG",
    src: "../assets/videos/cat_2.mp4",
    bookmarked: false,
  },
  {
    id: 2,
    name: "Cat 3",
    img: "../assets/thumbnails/cat3.PNG",
    src: "../assets/videos/cat_3.mp4",
    bookmarked: false,
  },
  {
    id: 3,
    name: "Cat 4",
    img: "../assets/thumbnails/cat4.PNG",
    src: "../assets/videos/cat_4.mp4",
    bookmarked: false,
  },
  {
    id: 4,
    name: "Cat 5",
    img: "../assets/thumbnails/cat5.PNG",
    src: "../assets/videos/cat_5.mp4",
    bookmarked: false,
  },
  {
    id: 5,
    name: "Cat 6",
    img: "../assets/thumbnails/cat6.PNG",
    src: "../assets/videos/cat_6.mp4",
    bookmarked: false,
  },
  {
    id: 6,
    name: "Cat 7",
    img: "../assets/thumbnails/cat7.PNG",
    src: "../assets/videos/cat_7.mp4",
    bookmarked: false,
  },
  {
    id: 7,
    name: "Cat 8",
    img: "../assets/thumbnails/cat8.PNG",
    src: "../assets/videos/cat_8.mp4",
    bookmarked: false,
  },
  {
    id: 8,
    name: "Cat 9",
    img: "../assets/thumbnails/cat9.PNG",
    src: "../assets/videos/cat_9.mp4",
    bookmarked: false,
  },
  {
    id: 9,
    name: "Cat 10",
    img: "../assets/thumbnails/cat10.PNG",
    src: "../assets/videos/cat_10.mp4",
    bookmarked: false,
  },
  {
    id: 10,
    name: "Cat 11",
    img: "../assets/thumbnails/cat11.PNG",
    src: "../assets/videos/cat_11.mp4",
    bookmarked: false,
  },
];
